#!/usr/bin/env bash
# Zul Tier-1 live bringup. Run ON THE SERVER after cloning the repo and
# installing the toolchain. Idempotent and safe: never overwrites existing
# keys or an existing genesis (that would change the chain identity).
#
#   ./scripts/init-live.sh
#   ZUL_L1_RPC_URL='https://your-l1-rpc-host/?api-key=...' ./scripts/init-live.sh
#
# Produces (all gitignored):
#   keys/{sequencer,faucet,fee_collector,ops}.json   chmod 600
#   config/genesis.toml                              chain identity
#   config/node.toml                                 node config
#   data/params/{transfer,unshield}.vk.bin           pool verifying keys
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CHAIN_NAME="${ZUL_CHAIN_NAME:-zul-live}"
# Native supply distribution (lamports; 1 ZUL = 1_000_000_000 lamports).
FAUCET_LAMPORTS="${ZUL_FAUCET_LAMPORTS:-1000000000000000000}"   # 1e9 ZUL
OPS_LAMPORTS="${ZUL_OPS_LAMPORTS:-500000000000000000}"          # 5e8 ZUL
# L1 (devnet) RPC for the bridge; left disabled until programs are deployed.
L1_RPC_URL="${ZUL_L1_RPC_URL:-https://api.devnet.solana.com}"

command -v solana-keygen >/dev/null 2>&1 || {
  echo "error: solana-keygen not found. Install the Solana/Agave toolchain first." >&2
  exit 1
}

mkdir -p keys data/params config
chmod 700 keys

gen_key() {
  local name="$1" path="keys/$1.json"
  # Logs go to stderr so `$(gen_key ...)` captures ONLY the pubkey.
  if [ -f "$path" ]; then
    echo "  keep   $path (exists)" >&2
  else
    solana-keygen new --no-bip39-passphrase --silent -o "$path" >/dev/null 2>&1
    chmod 600 "$path"
    echo "  create $path" >&2
  fi
  solana-keygen pubkey "$path"
}

echo "==> keypairs (keys/ is gitignored, chmod 600)"
SEQUENCER=$(gen_key sequencer)
FAUCET=$(gen_key faucet)
FEE_COLLECTOR=$(gen_key fee_collector)
OPS=$(gen_key ops)

# ---- genesis (write once; changing it forks the chain identity) ----------
if [ -f config/genesis.toml ]; then
  echo "==> config/genesis.toml exists — keeping it (chain already initialized)"
else
  echo "==> writing config/genesis.toml"
  CREATION_MS=$(( $(date +%s) * 1000 ))
  cat > config/genesis.toml <<EOF
# Zul live genesis. The blake3 hash of this content is the chain identity.
# Generated by scripts/init-live.sh — do not edit after the chain has booted.
chain_name = "$CHAIN_NAME"
creation_time_ms = $CREATION_MS
sequencer = "$SEQUENCER"
fee_collector = "$FEE_COLLECTOR"

[[allocations]]
# Faucet pool (backs requestAirdrop).
pubkey = "$FAUCET"
lamports = $FAUCET_LAMPORTS

[[allocations]]
# Operations reserve.
pubkey = "$OPS"
lamports = $OPS_LAMPORTS
EOF
fi

# ---- node config (safe to regenerate; holds no chain identity) -----------
echo "==> writing config/node.toml"
cat > config/node.toml <<EOF
[node]
data_dir = "$REPO_ROOT/data"
genesis_path = "$REPO_ROOT/config/genesis.toml"
sequencer_key_path = "$REPO_ROOT/keys/sequencer.json"
slot_duration_ms = 500

[rpc]
# 0.0.0.0 so wallets/explorer can reach it; lock down with ufw.
http_addr = "0.0.0.0:8899"
ws_addr = "0.0.0.0:8900"
faucet_enabled = true
faucet_max_lamports = 10000000000
faucet_key_path = "$REPO_ROOT/keys/faucet.json"

[l1]
# Disabled until the Anchor programs are deployed to devnet (Tier 3).
enabled = false
rpc_url = "$L1_RPC_URL"
settlement_program_id = ""
da_log_program_id = ""
bridge_authority_key_path = ""
batch_interval_slots = 120
EOF

# ---- pool verifying keys -> data/params ----------------------------------
if [ -f circuits/artifacts/transfer.vk.bin ] && [ -f circuits/artifacts/unshield.vk.bin ]; then
  cp circuits/artifacts/transfer.vk.bin circuits/artifacts/unshield.vk.bin data/params/
  echo "==> copied pool verifying keys to data/params/ (private transfers enabled)"
else
  echo "==> WARN: circuits/artifacts/*.vk.bin missing — shields will work but"
  echo "          transfers/unshields stay disabled until you build the circuits."
fi

cat <<EOF

==> done. summary
  chain         $CHAIN_NAME
  sequencer     $SEQUENCER
  fee_collector $FEE_COLLECTOR
  faucet        $FAUCET
  ops           $OPS
  l1.rpc_url    ${L1_RPC_URL%%\?*}$( [ "${L1_RPC_URL}" != "${L1_RPC_URL%%\?*}" ] && echo '?api-key=***' )

next:
  cd chain && cargo build --release -p zul-node
  ./target/release/zul-node --config $REPO_ROOT/config/node.toml
EOF
