#!/usr/bin/env bash
# Zul live bringup, per network. Run ON THE SERVER after cloning the repo and
# installing the toolchain. Idempotent and safe: never overwrites existing
# keys or an existing genesis (that would change the chain identity).
#
#   ZUL_NET=testnet ./scripts/init-live.sh
#   ZUL_NET=mainnet ./scripts/init-live.sh
#   ZUL_NET=mainnet ZUL_L1_RPC_URL='https://...mainnet...?api-key=...' ./scripts/init-live.sh
#
# Default network is testnet. Produces (all gitignored):
#   keys/<net>/{sequencer,fee_collector,ops[,faucet]}.json   chmod 600
#   config/<net>/genesis.toml                                chain identity
#   config/<net>/node.toml                                   node config
#   data/<net>/params/{transfer,unshield}.vk.bin            pool verifying keys
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

NET="${ZUL_NET:-testnet}"
case "$NET" in
  testnet|mainnet) ;;
  *) echo "error: ZUL_NET must be 'testnet' or 'mainnet' (got '$NET')" >&2; exit 1 ;;
esac

# Per-network defaults.
if [ "$NET" = "mainnet" ]; then
  CHAIN_NAME="${ZUL_CHAIN_NAME:-zul-mainnet-1}"
  L1_RPC_URL="${ZUL_L1_RPC_URL:-https://api.mainnet-beta.solana.com}"
  FAUCET_ENABLED=false
  BATCH_INTERVAL=600
else
  CHAIN_NAME="${ZUL_CHAIN_NAME:-zul-testnet-1}"
  L1_RPC_URL="${ZUL_L1_RPC_URL:-https://api.devnet.solana.com}"
  FAUCET_ENABLED=true
  BATCH_INTERVAL=120
fi

# Native supply distribution (lamports; 1 ZUL = 1_000_000_000 lamports).
FAUCET_LAMPORTS="${ZUL_FAUCET_LAMPORTS:-1000000000000000000}"   # 1e9 ZUL
OPS_LAMPORTS="${ZUL_OPS_LAMPORTS:-500000000000000000}"          # 5e8 ZUL

KEYS_DIR="keys/$NET"
DATA_DIR="$REPO_ROOT/data/$NET"
CONFIG_DIR="config/$NET"

command -v solana-keygen >/dev/null 2>&1 || {
  echo "error: solana-keygen not found. Install the Solana/Agave toolchain first." >&2
  exit 1
}

mkdir -p "$KEYS_DIR" "$DATA_DIR/params" "$CONFIG_DIR"
chmod 700 "$KEYS_DIR"

gen_key() {
  local name="$1" path="$KEYS_DIR/$1.json"
  # Logs go to stderr so `$(gen_key ...)` captures ONLY the pubkey.
  if [ -f "$path" ]; then
    echo "  keep   $path (exists)" >&2
  else
    solana-keygen new --no-bip39-passphrase --silent -o "$path" >/dev/null 2>&1
    chmod 600 "$path"
    echo "  create $path" >&2
  fi
  solana-keygen pubkey "$path"
}

echo "==> [$NET] keypairs ($KEYS_DIR is gitignored, chmod 600)"
SEQUENCER=$(gen_key sequencer)
FEE_COLLECTOR=$(gen_key fee_collector)
OPS=$(gen_key ops)
if [ "$FAUCET_ENABLED" = true ]; then
  FAUCET=$(gen_key faucet)
fi

# ---- genesis (write once; changing it forks the chain identity) ----------
if [ -f "$CONFIG_DIR/genesis.toml" ]; then
  echo "==> $CONFIG_DIR/genesis.toml exists — keeping it (chain already initialized)"
else
  echo "==> writing $CONFIG_DIR/genesis.toml"
  CREATION_MS=$(( $(date +%s) * 1000 ))
  {
    echo "# Zul live genesis ($NET). The blake3 hash of this content is the chain identity."
    echo "# Generated by scripts/init-live.sh — do not edit after the chain has booted."
    echo "chain_name = \"$CHAIN_NAME\""
    echo "creation_time_ms = $CREATION_MS"
    echo "sequencer = \"$SEQUENCER\""
    echo "fee_collector = \"$FEE_COLLECTOR\""
    echo ""
    if [ "$FAUCET_ENABLED" = true ]; then
      echo "[[allocations]]"
      echo "# Faucet pool (backs requestAirdrop)."
      echo "pubkey = \"$FAUCET\""
      echo "lamports = $FAUCET_LAMPORTS"
      echo ""
    fi
    echo "[[allocations]]"
    echo "# Operations / gas-onboarding reserve."
    echo "pubkey = \"$OPS\""
    echo "lamports = $OPS_LAMPORTS"
  } > "$CONFIG_DIR/genesis.toml"
fi

# ---- node config (safe to regenerate; holds no chain identity) -----------
echo "==> writing $CONFIG_DIR/node.toml"
{
  echo "[node]"
  echo "network = \"$NET\""
  echo "data_dir = \"$DATA_DIR\""
  echo "genesis_path = \"$REPO_ROOT/$CONFIG_DIR/genesis.toml\""
  echo "sequencer_key_path = \"$REPO_ROOT/$KEYS_DIR/sequencer.json\""
  echo "slot_duration_ms = 500"
  echo ""
  echo "[rpc]"
  echo "# 0.0.0.0 so wallets/explorer can reach it; lock down with ufw."
  echo "http_addr = \"0.0.0.0:8899\""
  echo "ws_addr = \"0.0.0.0:8900\""
  if [ "$FAUCET_ENABLED" = true ]; then
    echo "faucet_enabled = true"
    echo "faucet_max_lamports = 10000000000"
    echo "faucet_key_path = \"$REPO_ROOT/$KEYS_DIR/faucet.json\""
  else
    echo "# No faucet on mainnet: ZUL is real gas."
    echo "faucet_enabled = false"
  fi
  echo ""
  echo "[l1]"
  echo "# Disabled until the Anchor programs are deployed and the authority funded."
  echo "enabled = false"
  echo "rpc_url = \"$L1_RPC_URL\""
  echo "settlement_program_id = \"\""
  echo "da_log_program_id = \"\""
  echo "bridge_authority_key_path = \"\""
  echo "batch_interval_slots = $BATCH_INTERVAL"
} > "$CONFIG_DIR/node.toml"

# ---- pool verifying keys -> data/<net>/params ----------------------------
if [ -f circuits/artifacts/transfer.vk.bin ] && [ -f circuits/artifacts/unshield.vk.bin ]; then
  cp circuits/artifacts/transfer.vk.bin circuits/artifacts/unshield.vk.bin "$DATA_DIR/params/"
  echo "==> copied pool verifying keys to $DATA_DIR/params/ (private transfers enabled)"
else
  echo "==> WARN: circuits/artifacts/*.vk.bin missing — shields will work but"
  echo "          transfers/unshields stay disabled until you build the circuits."
fi

cat <<EOF

==> done. summary [$NET]
  chain         $CHAIN_NAME
  sequencer     $SEQUENCER
  fee_collector $FEE_COLLECTOR
$( [ "$FAUCET_ENABLED" = true ] && echo "  faucet        $FAUCET" )
  ops           $OPS
  l1.rpc_url    ${L1_RPC_URL%%\?*}$( [ "${L1_RPC_URL}" != "${L1_RPC_URL%%\?*}" ] && echo '?api-key=***' )

next:
  cd chain && cargo build --release -p zul-node
  ./target/release/zul-node --config $REPO_ROOT/$CONFIG_DIR/node.toml
EOF
